name    'antikhttpd'
version '1.0.1'
source 'git@github.com:puppetlabs/puppetlabs-motd.git'
author 'TomasAntos'
license 'freeware'
summary 'A simple module to install, configure and start apache server'
